apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-storage
  namespace: <NAMESPACE>
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-provisioner
